#!/bin/bash

if [[ $1 == on ]] ; then
    networksetup -setairportpower airport on
elif [[ $1 == off ]] ; then
    networksetup -setairportpower airport off
elif [[ -z $1 ]] ; then
    networksetup -getairportpower airport
elif [[ $1 == cycle ]] ; then
    networksetup -setairportpower airport off
    networksetup -setairportpower airport on
else
    echo "Usage: $0 [on|off]"
fi
