#!/bin/sh

if [[ -z $1 ]] ; then
	defaults write com.apple.finder AppleShowAllFiles TRUE
	killall Finder
elif [[ $1 == off ]] ; then
	defaults write com.apple.finder AppleShowAllFiles False
	killall Finder
fi
