#!/bin/sh

rsync --rsync-path='rsync --log-file=$HOME/.rsync/rsync_recv.log' \
      --log-file=$HOME/.rsync/rsync_send.log --human-readable \
      --force --delete --delete-during \
      --archive --no-p --no-g --chmod=ugo=rwX \
      --compress --sparse \
      --stats --progress $@

# --safe-links --checksum --xattrs --ipv6 --cvs-exclude --exclude=".git/"
# --include='*.bak' \
